FROM node:18

RUN npm install -g express
RUN npm install -g mongoose
RUN npm install -g nodemon

WORKDIR /home/app

# Copy the Files of Configuration
COPY package*.json /home/app

# Install the Dependencies
RUN npm install

# Copy the Rest of the Code
COPY . /home/app

EXPOSE 3000

CMD ["npm", "run", "dev"]