FROM node:18

WORKDIR /home/app

# Copy the Files of Configuration
COPY package*.json /home/app

RUN npm cache clean --force
RUN rm -rf node_modules package-lock.json

# RUN npm install express --save
# RUN npm install mongoose --save
# RUN npm install nodemon --save
RUN npm install --save

# Copy the Rest of the Code
COPY . /home/app

EXPOSE 3000

CMD ["npm", "run", "dev"]